### ISSUE TITLE
Deploiement de l'authentification sur Vercel (Prisma)

### ISSUE THREAD

**Issue by adammehdaoui** [adammehdaoui/jikan_next#4]
<html>
<body>

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
--
14:32:13.647 | In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report
14:32:13.648 | at new PrismaClient (/vercel/path0/node_modules/.prisma/client/default.js:43:11)
14:32:13.648 | at 75724 (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:1777)
14:32:13.648 | at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
14:32:13.648 | at 67650 (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:1127)
14:32:13.649 | at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
14:32:13.649 | at r (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:2146)
14:32:13.649 | at /vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:2177
14:32:13.655 | at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1206)
14:32:13.656 | at /vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:2159
14:32:13.656 | at Object.<anonymous> (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:2205)
14:32:13.666 |  
14:32:13.669 | > Build error occurred
14:32:13.670 | Error: Failed to collect page data for /api/auth/[...nextauth]
14:32:13.670 | at /vercel/path0/node_modules/next/dist/build/utils.js:1220:15
14:32:13.670 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
14:32:13.670 | type: 'Error'

</body>
</html>

**Comment by adammehdaoui** [comment]
Résolution en enlevant l'output perso pour la génération du client prisma (./prisma/generated/ -> default)
